name: planning-transformer
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - anaconda
  - cudatoolkit=10.2.89
  - python=3.10.12
  - numpy=1.26.2
  - tensorboard=2.5.0
  - pip
  - pip:
    - gym==0.23.1
    - git+https://github.com/rail-berkeley/d4rl@master#egg=d4rl
#    - mujoco==2.2.1 (needed for one of the envs but I forgot which)
#    - mujoco-py==2.1.2.14
    - mujoco==3.1.4
    - torch==1.11.0
    - pyrallis==0.3.1
    - wandb==0.16.0
    - cython==0.29.36
    - opencv-python==4.9.0
    - shapely
    - gym-pusht
    - git+https://github.com/mees/calvin.git@main#egg=calvin
    - git+https://github.com/huggingface/lerobot.git@main#egg=lerobot
#    - gym-xarm
