name: planning-transformer
channels:
  - pytorch
dependencies:
  - anaconda
  - cudatoolkit=10.2.89
  - python=3.10.12
  - numpy=1.26.2
  - pip
  - pip:
    - gym==0.23.1
    - git+https://github.com/rail-berkeley/d4rl@master#egg=d4rl
    - mujoco==2.2.1
    - tensorboard==2.5.0
    - torch==1.11.0
    - pyrallis==0.3.1
    - wandb==0.16.0