attention_dropout: 0.15 #0.1
batch_size: 128 #64 #256
betas:
- 0.9
- 0.999
checkpoints_path: "./checkpoints/kitchen_mixed/PDT-oracle"
clip_grad: 0.25
deterministic_torch: false
device: cuda
embedding_dim: 256
embedding_dropout: 0.1 #0.1
env_name: "kitchen-mixed-v0"
episode_len: 280
eval_episodes: 15 #15
eval_every: 5000
eval_seed: 43 #42 or -1 to seed every run the same
group: "dt-kitchen-mixed-PDT"
learning_rate: 0.0002 #0.0001 #0.004
max_action: 1.0
name: "PDT-oracle"
num_heads: 2
num_layers: 3
num_workers: 4
project: "CORL"
residual_dropout: 0.15 #0.1
reward_scale: 1.0
seq_len: 10
target_returns: [4.0]
train_seed: 16 #10
update_steps: 100000
warmup_steps: 10000
weight_decay: 0.0001
log_attn_weights: 1
log_attn_every: 250
record_video: 1
run_name: "run_10"
eval_offline_every: 5000
bg_image: "./bg_images/kitchen_bg.png"
eval_path_plot_every: 2500
num_plan_points: 10
plan_bar_visualisation: false
replanning_interval: 10 #80
num_eval_videos: 0 # doesn't work for kitchen so don't bother
action_noise_scale: 0.0 # 0.4
use_log_distance_plans: true # true
plan_max_trajectory_ratio: 0.5 # 0.5
state_noise_scale: 0.0 # 0.0
plan_type: "split" #split
use_two_phase_training: false # false
is_goal_conditioned: true # true
goal_indices: [17,18,22,23, 24, 25, 26, 27, 28, 29]
#plan_indices: [17,18,22,23, 24, 25, 26, 27, 28, 29]
path_viz_indices: [23,24]
plans_use_actions: true
non_plan_downweighting: 0 #-2
use_goal_space_first_state_token: true
use_timestep_embedding: true