attention_dropout: 0.1
batch_size: 64
betas:
- 0.9
- 0.999
checkpoints_path: "./checkpoints/medium_diverse/PDT-manual"
clip_grad: 0.25
deterministic_torch: false
device: cuda
embedding_dim: 64
embedding_dropout: 0.1
env_name: "antmaze-medium-diverse-v2"
episode_len: 1000
eval_episodes: 10
eval_every: 10000
eval_seed: 42
group: "dt-antmaze-medium-PDT-manual"
learning_rate: 0.0001
max_action: 1.0
name: "PDT-manual"
num_heads: 1
num_layers: 3
num_workers: 4
project: "CORL"
residual_dropout: 0.1
reward_scale: 1.0
seq_len: 20
target_returns: [1.0]
train_seed: 10
update_steps: 100000
warmup_steps: 10000
weight_decay: 0.0001
log_attn_weights: 1
log_attn_every: 250
record_video: 1
run_name: "run_3"
num_planning_tokens: 0
eval_offline_every: 1000
bg_image: "./antmaze_medium_bg.png"
eval_path_plot_every: 5000