attention_dropout: 0.1
batch_size: 64
betas:
- 0.9
- 0.999
checkpoints_path: "../checkpoints/PDT"
clip_grad: 0.25
deterministic_torch: false
device: cuda
embedding_dim: 128
embedding_dropout: 0.1
env_name: "antmaze-umaze-v2"
episode_len: 1000
eval_episodes: 20
eval_every: 10000
eval_seed: 42
group: "dt-antmaze-umaze-v2-multiseed-v0"
learning_rate: 0.0001
max_action: 1.0
name: "PDT"
num_heads: 2
num_layers: 3
num_workers: 4
project: "CORL"
residual_dropout: 0.1
reward_scale: 1.0
seq_len: 20
target_returns: [1.0, 0.5]
train_seed: 10
update_steps: 100000
warmup_steps: 10000
weight_decay: 0.0001
log_attn_weights: 1
log_attn_every: 100
record_video: 1
