attention_dropout: 0.15 #0.1
batch_size: 128 #64 #256
betas:
- 0.9
- 0.999
checkpoints_path: "./checkpoints/calvin_mixed/PDT-oracle"
clip_grad: 0.25
deterministic_torch: false
device: cuda
embedding_dim: 192
embedding_dropout: 0.1 #0.1
env_name: "calvin-v0"
episode_len: 1000
eval_episodes: 15 #15
eval_every: 5000
eval_seed: 43 #42 or -1 to seed every run the same
group: "dt-calvin-PDT"
learning_rate: 0.0004 #0.0002
max_action: 1.0
name: "PDT-oracle"
num_heads: 2
num_layers: 3
num_workers: 4
project: "CORL"
residual_dropout: 0.15 #0.1
reward_scale: 1.0
seq_len: 10
target_returns: [4.0]
train_seed: 16 #10
update_steps: 200000
warmup_steps: 10000
weight_decay: 0.0001
log_attn_weights: 1
log_attn_every: 250
record_video: 1
run_name: "run2"
eval_offline_every: 5000
bg_image: "kitchen_bg.png"
eval_path_plot_every: 2500
num_plan_points: 10
plan_bar_visualisation: false
replanning_interval: 5 #80
num_eval_videos: 1 # Video rendering can be slow for kitchen env
action_noise_scale: 0.0 # 0.4
plan_max_trajectory_ratio: 1.0 # 0.5
state_noise_scale: 0.0 # 0.0
plan_disabled: False
use_two_phase_training: false # false
is_goal_conditioned: true # true
goal_indices: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,20]
#plan_indices: [17,18,22,23, 24, 25, 26, 27, 28, 29]
path_viz_indices: [0,1]
plans_use_actions: True
non_plan_downweighting: 0 #-2
use_timestep_embedding: true
plan_combine_observations: False
plan_sampling_method: 2 # 1: fixed-time", 2: fixed-distance", 3: log-time", 4: log-distance
plan_use_relative_states: True
goal_representation: 3 # 1: Absolute Goal, 2: Relative goal, 3: State project to Goal and Absolute Goal